.PHONY: all, clean, build, deploy, local

help:
	@echo "Please use \`make <target>' where <target> is one of"
	@echo "  all       to build and deploy"
	@echo "  clean     to remove all build artifacts"
	@echo "  local     to run the app locally"
	@echo "  build     to build the app"
	@echo "  deploy    to deploy the app"

local:
	npm run dev

build:
	npm run build

deploy:
	npm run deploy