import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { useState, useEffect, use } from 'react';
import { useAccount } from 'wagmi';
import { FaUserGear, FaIdCard, FaFileInvoice } from "react-icons/fa6";



const Home: NextPage = () => {

  const [isClient, setIsClient] = useState(false);
  const [userConected, setUserConected] = useState<any>(null);
  const { address, isConnected } = useAccount();
  useEffect(() => {
    setIsClient(true);
  }, []);




  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className={styles.header}>
      <ConnectButton
            label='Conectar a red'
            showBalance={{
              smallScreen: false,
              largeScreen: true,
            }}
            accountStatus="address"
            chainStatus={{
              smallScreen: "none",
              largeScreen: "icon",
            }}
      />
      </header>


      <main className={styles.main}>
      <div className={styles.container__treeButtons}>
        <button className={styles.button_toPanel} onClick={() => window.location.href='/panel'}>
          <p>Ir a panel de empleado</p> 
          <p>
            <FaUserGear
              size={40}
              color={'#fff'}
            />
          </p>
        </button>
        <button className={styles.button__toMyData} onClick={() => window.location.href='/credencialDigital'}>
          <p>Ir a mi credencial digital</p> 
          <p>
            <FaIdCard
              size={40}
              color={'#fff'}
            />
          </p>
        </button>
        <button className={styles.button__toGetData} onClick={() => window.location.href='/datos'}>
          <p>Obtener datos</p>
          <p>
            <FaFileInvoice
              size={40}
              color={'#fff'}
            />
          </p>
        </button>
        </div>

      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
